# Generated by Django 4.2.16 on 2024-12-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watchAgain',
            field=models.BooleanField(default=False),
        ),
    ]
